# Generated by Django 5.0.4 on 2024-04-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255, null=True)),
                ('street_name', models.TextField(null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('needs_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('is_candidate', models.BooleanField(default=False)),
                ('office', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('report_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('classification', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.entity')),
            ],
        ),
    ]
